# Generated by Django 2.1.5 on 2020-07-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
