# Generated by Django 2.1.5 on 2020-07-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commu', '0004_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
