# Generated by Django 2.1.5 on 2020-07-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forcastdata',
            options={'ordering': ['id'], 'verbose_name_plural': 'forecasts'},
        ),
    ]
