# Generated by Django 2.1.5 on 2020-07-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200726_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namaesamri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airTemperature', models.FloatField()),
                ('waterTemperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('waveDirection', models.FloatField()),
                ('waveHeight', models.FloatField()),
                ('wavePeriod', models.FloatField()),
                ('windDirection', models.FloatField()),
                ('gust', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'forecasts',
                'ordering': ['id'],
            },
        ),
    ]
