# Generated by Django 2.1.5 on 2020-07-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_namaesamri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namaesamri',
            options={'ordering': ['id'], 'verbose_name_plural': 'namaesamri'},
        ),
    ]
