# Generated by Django 2.1.5 on 2020-08-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20200731_0251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Namaesamri',
            new_name='Jumunjin',
        ),
        migrations.AlterModelOptions(
            name='jumunjin',
            options={'ordering': ['id'], 'verbose_name_plural': 'jumunjin'},
        ),
        migrations.RenameField(
            model_name='jumunjin',
            old_name='airTemperature',
            new_name='airTemperature2',
        ),
        migrations.RenameField(
            model_name='jumunjin',
            old_name='gust',
            new_name='gust2',
        ),
        migrations.RenameField(
            model_name='jumunjin',
            old_name='waterTemperature',
            new_name='precipitation2',
        ),
        migrations.RenameField(
            model_name='jumunjin',
            old_name='precipitation',
            new_name='waterTemperature2',
        ),
        migrations.RenameField(
            model_name='jumunjin',
            old_name='waveDirection',
            new_name='waveDirection2',
        ),
        migrations.RenameField(
            model_name='jumunjin',
            old_name='waveHeight',
            new_name='waveHeight2',
        ),
        migrations.RenameField(
            model_name='jumunjin',
            old_name='wavePeriod',
            new_name='wavePeriod2',
        ),
        migrations.RenameField(
            model_name='jumunjin',
            old_name='windDirection',
            new_name='windDirection2',
        ),
    ]
