# Generated by Django 2.1.5 on 2020-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20200802_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcastdata',
            name='spot',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
    ]
