# Generated by Django 2.1.5 on 2020-08-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20200802_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcastdata',
            name='airTemperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forcastdata',
            name='gust',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forcastdata',
            name='precipitation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forcastdata',
            name='spot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='forcastdata',
            name='waterTemperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forcastdata',
            name='waveDirection',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forcastdata',
            name='waveHeight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forcastdata',
            name='wavePeriod',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forcastdata',
            name='windDirection',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
    ]
