# Generated by Django 2.1.5 on 2020-08-02 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0010_auto_20200802_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
